project_id = "xtcicjrpznawnwvjdqhe"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.get-maps-key]
    verify_jwt = false
  [functions.mapgis-consulta]
    verify_jwt = true
  [functions.process-email-queue]
    verify_jwt = true
  [functions.wompi-webhook]
    verify_jwt = false
